webStudent\EtudiantBundle\Entity\Etudiant:
    type: entity
    table: null
    repositoryClass: webStudent\EtudiantBundle\Entity\EtudiantRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        date:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
