webStudent\EtudiantBundle\Entity\Enseignant:
    type: entity
    table: null
    repositoryClass: webStudent\EtudiantBundle\Entity\EnseignantRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
