<?php

namespace webStudent\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{

	public function rechercherEtudiant($pNom)
{
      // Création de la requête
      $queryBuilder = $this->createQueryBuilder('e')
                                 ->where('e.nom like :leNom')
                                 ->setParameter('leNom', $pNom)
                                 ->orderBy('e.nom', 'ASC') ;
    // On récupère la Query à partir du QueryBuilder
    $query = $queryBuilder->getQuery();
    // On récupère les résultats à partir de la Query
    $resultats = $query->getResult();
    // On retourne ces résultats
    return $resultats;
}
    public function find($id)
{
    $repository = $this->getDoctrine()
    ->getManager()
    ->getRepository('webStageEtudiantBundle:Section');
    $section = $repository->find($id);

}

 public function find2($id)
{
    $repository = $this->getDoctrine()
    ->getManager()
    ->getRepository('webStageEtudiantBundle:Etudiant');
    $etudiant = $repository->find2($id);

}    

}
