webStudent\EtudiantBundle\Entity\Entreprise:
    type: entity
    table: null
    repositoryClass: webStudent\EtudiantBundle\Entity\EntrepriseRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: '8'
        raisonSociale:
            type: string
            length: '100'
            column: 'Raison sociale'
        rue:
            type: string
            length: '100'
            column: Rue
        ville:
            type: string
            length: '100'
            column: Ville
        cp:
            type: string
            length: '6'
            column: Cp
    lifecycleCallbacks: {  }
